/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package es.tpv_bar.gui.botones;

import es.tpv_bar.VentanaTPV;
import es.tpv_bar.gui.DlTecladoNum;
import es.tpv_bar.persistencia.pojos.Productos;

/**
 *
 * @author aperalta
 */
public class BTLineas extends javax.swing.JPanel {

    /**
     * Creates new form BTLineas
     */
    public BTLineas() {
        initComponents();
    }
    Productos producto;
    VentanaTPV parent;
    public BTLineas(Productos producto,VentanaTPV parent) {
        this();
        this.parent = parent;
        this.producto = producto;
        this.lbProducto.setText(this.producto.getNombre());
        this.txPrecio.setText(this.producto.getPrecio().toString());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txPrecio1 = new javax.swing.JTextField();
        lbProducto = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        txPrecio = new javax.swing.JTextField();

        txPrecio1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txPrecio1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txPrecio1.setText("0.0");
        txPrecio1.setToolTipText("");

        lbProducto.setText("Producto");

        txPrecio.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txPrecio.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txPrecio.setText("0.0");
        txPrecio.setToolTipText("");
        txPrecio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txPrecioMouseClicked(evt);
            }
        });
        txPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txPrecioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jCheckBox1)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lbProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txPrecioActionPerformed

    private void txPrecioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txPrecioMouseClicked
      new DlTecladoNum(parent,true,this.txPrecio).setVisible(true);
    }//GEN-LAST:event_txPrecioMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel lbProducto;
    private javax.swing.JTextField txPrecio;
    private javax.swing.JTextField txPrecio1;
    // End of variables declaration//GEN-END:variables
}
