package es.tpv_bar.persistencia.pojos;
// Generated 14-may-2012 18:52:04 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Atipicas generated by hbm2java
 */
@Entity
@Table(name="atipicas"
    ,catalog="mydb"
)
public class Atipicas  implements java.io.Serializable {


     private Integer id;
     private Productos productos;
     private Bloqueubicacion bloqueubicacion;
     private int tipo;
     private Double precio;

    public Atipicas() {
    }

	
    public Atipicas(Productos productos, Bloqueubicacion bloqueubicacion, int tipo) {
        this.productos = productos;
        this.bloqueubicacion = bloqueubicacion;
        this.tipo = tipo;
    }
    public Atipicas(Productos productos, Bloqueubicacion bloqueubicacion, int tipo, Double precio) {
       this.productos = productos;
       this.bloqueubicacion = bloqueubicacion;
       this.tipo = tipo;
       this.precio = precio;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="productos", nullable=false)
    public Productos getProductos() {
        return this.productos;
    }
    
    public void setProductos(Productos productos) {
        this.productos = productos;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="bloqueubicacion", nullable=false)
    public Bloqueubicacion getBloqueubicacion() {
        return this.bloqueubicacion;
    }
    
    public void setBloqueubicacion(Bloqueubicacion bloqueubicacion) {
        this.bloqueubicacion = bloqueubicacion;
    }
    
    @Column(name="tipo", nullable=false)
    public int getTipo() {
        return this.tipo;
    }
    
    public void setTipo(int tipo) {
        this.tipo = tipo;
    }
    
    @Column(name="precio", precision=22, scale=0)
    public Double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Double precio) {
        this.precio = precio;
    }




}


