package es.tpv_bar.persistencia.pojos;
// Generated 18-abr-2012 16:51:34 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Caja generated by hbm2java
 */
@Entity
@Table(name="Caja"
    ,catalog="mydb"
)
public class Caja  implements java.io.Serializable {


     private Integer idCaja;
     private Date fecha;
     private double movimiento;
     private double saldo;
     private Integer idCamarero;
     private Integer idCabezera;

    public Caja() {
    }

	
    public Caja(Date fecha, double movimiento, double saldo) {
        this.fecha = fecha;
        this.movimiento = movimiento;
        this.saldo = saldo;
    }
    public Caja(Date fecha, double movimiento, double saldo, Integer idCamarero, Integer idCabezera) {
       this.fecha = fecha;
       this.movimiento = movimiento;
       this.saldo = saldo;
       this.idCamarero = idCamarero;
       this.idCabezera = idCabezera;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idCaja", unique=true, nullable=false)
    public Integer getIdCaja() {
        return this.idCaja;
    }
    
    public void setIdCaja(Integer idCaja) {
        this.idCaja = idCaja;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha", nullable=false, length=19)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    
    @Column(name="movimiento", nullable=false, precision=22, scale=0)
    public double getMovimiento() {
        return this.movimiento;
    }
    
    public void setMovimiento(double movimiento) {
        this.movimiento = movimiento;
    }
    
    @Column(name="saldo", nullable=false, precision=22, scale=0)
    public double getSaldo() {
        return this.saldo;
    }
    
    public void setSaldo(double saldo) {
        this.saldo = saldo;
    }
    
    @Column(name="idCamarero")
    public Integer getIdCamarero() {
        return this.idCamarero;
    }
    
    public void setIdCamarero(Integer idCamarero) {
        this.idCamarero = idCamarero;
    }
    
    @Column(name="idCabezera")
    public Integer getIdCabezera() {
        return this.idCabezera;
    }
    
    public void setIdCabezera(Integer idCabezera) {
        this.idCabezera = idCabezera;
    }




}


