package es.tpv_bar.persistencia.pojos;
// Generated 19-sep-2016 11:23:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Camarero generated by hbm2java
 */
@Entity
@Table(name="camarero"
)
public class Camarero  implements java.io.Serializable {


     private Integer idCamarero;
     private Empresas empresas;
     private String nombre;
     private String apellidos;
     private Integer telefono;
     private boolean activo;
     private Set<Cabezera> cabezeras = new HashSet<Cabezera>(0);
     private Set<Caja> cajas = new HashSet<Caja>(0);

    public Camarero() {
    }

	
    public Camarero(Empresas empresas, boolean activo) {
        this.empresas = empresas;
        this.activo = activo;
    }
    public Camarero(Empresas empresas, String nombre, String apellidos, Integer telefono, boolean activo, Set<Cabezera> cabezeras, Set<Caja> cajas) {
       this.empresas = empresas;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.telefono = telefono;
       this.activo = activo;
       this.cabezeras = cabezeras;
       this.cajas = cajas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IdCamarero", nullable=false)
    public Integer getIdCamarero() {
        return this.idCamarero;
    }
    
    public void setIdCamarero(Integer idCamarero) {
        this.idCamarero = idCamarero;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdEmpresa", nullable=false)
    public Empresas getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Empresas empresas) {
        this.empresas = empresas;
    }

    
    @Column(name="Nombre", length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="Apellidos", length=100)
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    
    @Column(name="Telefono")
    public Integer getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Integer telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="Activo", nullable=false)
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="camarero")
    public Set<Cabezera> getCabezeras() {
        return this.cabezeras;
    }
    
    public void setCabezeras(Set<Cabezera> cabezeras) {
        this.cabezeras = cabezeras;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="camarero")
    public Set<Caja> getCajas() {
        return this.cajas;
    }
    
    public void setCajas(Set<Caja> cajas) {
        this.cajas = cajas;
    }

    @Override
    public String toString() {
        return this.nombre; //To change body of generated methods, choose Tools | Templates.
    }



}


