package es.tpv_bar.persistencia.pojos;
// Generated 13-abr-2012 9:10:04 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Linea generated by hbm2java
 */
@Entity
@Table(name="Linea"
    ,catalog="mydb"
)
public class Linea  implements java.io.Serializable {


     private Integer idLinea;
     private Servicios servicios;
     private Productos productos;
     private Cabezera cabezera;
     private Double precio;
     private Double catidad;
     private Double total;

    public Linea() {
    }

	
    public Linea(Servicios servicios, Productos productos) {
        this.servicios = servicios;
        this.productos = productos;
    }
    public Linea(Servicios servicios, Productos productos, Cabezera cabezera, Double precio, Double catidad, Double total) {
       this.servicios = servicios;
       this.productos = productos;
       this.cabezera = cabezera;
       this.precio = precio;
       this.catidad = catidad;
       this.total = total;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="IdLinea", unique=true, nullable=false)
    public Integer getIdLinea() {
        return this.idLinea;
    }
    
    public void setIdLinea(Integer idLinea) {
        this.idLinea = idLinea;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdServiceo", nullable=false)
    public Servicios getServicios() {
        return this.servicios;
    }
    
    public void setServicios(Servicios servicios) {
        this.servicios = servicios;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdProductos", nullable=false)
    public Productos getProductos() {
        return this.productos;
    }
    
    public void setProductos(Productos productos) {
        this.productos = productos;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdCabezera")
    public Cabezera getCabezera() {
        return this.cabezera;
    }
    
    public void setCabezera(Cabezera cabezera) {
        this.cabezera = cabezera;
    }
    
    @Column(name="Precio", precision=22, scale=0)
    public Double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Double precio) {
        this.precio = precio;
    }
    
    @Column(name="catidad", precision=22, scale=0)
    public Double getCatidad() {
        return this.catidad;
    }
    
    public void setCatidad(Double catidad) {
        this.catidad = catidad;
    }
    
    @Column(name="Total", precision=22, scale=0)
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }




}


