package es.tpv_bar.persistencia.pojos;
// Generated 18-abr-2012 16:51:34 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Linea generated by hbm2java
 */
@Entity
@Table(name="Linea"
    ,catalog="mydb"
)
public class Linea  implements java.io.Serializable {


     private Integer idLinea;
     private Productos productos;
     private Cabezera cabezera;
     private Ubicacion ubicacion;
     private Double precio;
     private Double catidad;
     private Double total;
     private boolean cobrado;

    public Linea() {
    }

	
    public Linea(Productos productos, Ubicacion ubicacion, boolean cobrado) {
        this.productos = productos;
        this.ubicacion = ubicacion;
        this.cobrado = cobrado;
    }
    public Linea(Productos productos, Cabezera cabezera, Ubicacion ubicacion, Double precio, Double catidad, Double total, boolean cobrado) {
       this.productos = productos;
       this.cabezera = cabezera;
       this.ubicacion = ubicacion;
       this.precio = precio;
       this.catidad = catidad;
       this.total = total;
       this.cobrado = cobrado;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="IdLinea", unique=true, nullable=false)
    public Integer getIdLinea() {
        return this.idLinea;
    }
    
    public void setIdLinea(Integer idLinea) {
        this.idLinea = idLinea;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdProductos", nullable=false)
    public Productos getProductos() {
        return this.productos;
    }
    
    public void setProductos(Productos productos) {
        this.productos = productos;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdCabezera")
    public Cabezera getCabezera() {
        return this.cabezera;
    }
    
    public void setCabezera(Cabezera cabezera) {
        this.cabezera = cabezera;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdUbicacion", nullable=false)
    public Ubicacion getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(Ubicacion ubicacion) {
        this.ubicacion = ubicacion;
    }
    
    @Column(name="Precio", precision=22, scale=0)
    public Double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Double precio) {
        this.precio = precio;
    }
    
    @Column(name="catidad", precision=22, scale=0)
    public Double getCatidad() {
        return this.catidad;
    }
    
    public void setCatidad(Double catidad) {
        this.catidad = catidad;
    }
    
    @Column(name="Total", precision=22, scale=0)
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }
    
    @Column(name="cobrado", nullable=false)
    public boolean isCobrado() {
        return this.cobrado;
    }
    
    public void setCobrado(boolean cobrado) {
        this.cobrado = cobrado;
    }




}


