package es.tpv_bar.persistencia.pojos;
// Generated 13-abr-2012 9:10:04 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Servicios generated by hbm2java
 */
@Entity
@Table(name="Servicios"
    ,catalog="mydb"
)
public class Servicios  implements java.io.Serializable {


     private Integer idServiceo;
     private Ubicacion ubicacion;
     private Boolean estado;
     private Set<Linea> lineas = new HashSet<Linea>(0);

    public Servicios() {
    }

	
    public Servicios(Ubicacion ubicacion) {
        this.ubicacion = ubicacion;
    }
    public Servicios(Ubicacion ubicacion, Boolean estado, Set<Linea> lineas) {
       this.ubicacion = ubicacion;
       this.estado = estado;
       this.lineas = lineas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="IdServiceo", unique=true, nullable=false)
    public Integer getIdServiceo() {
        return this.idServiceo;
    }
    
    public void setIdServiceo(Integer idServiceo) {
        this.idServiceo = idServiceo;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdUbicacion", nullable=false)
    public Ubicacion getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(Ubicacion ubicacion) {
        this.ubicacion = ubicacion;
    }
    
    @Column(name="Estado")
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="servicios")
    public Set<Linea> getLineas() {
        return this.lineas;
    }
    
    public void setLineas(Set<Linea> lineas) {
        this.lineas = lineas;
    }




}


